//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gfgfg
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Прикол.
    /// </summary>
    // *** Start programmer edit section *** (Прикол CustomAttributes)

    // *** End programmer edit section *** (Прикол CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПриколE", new string[] {
            "тит as \'Тит\'"})]
    [View("ПриколL", new string[] {
            "тит as \'Тит\'"})]
    public class Прикол : IIS.Gfgfg.Наслед
    {
        
        // *** Start programmer edit section *** (Прикол CustomMembers)

        // *** End programmer edit section *** (Прикол CustomMembers)

        
        /// <summary>
        /// тит.
        /// </summary>
        // *** Start programmer edit section *** (Прикол.тит CustomAttributes)

        // *** End programmer edit section *** (Прикол.тит CustomAttributes)
        [StrLen(255)]
        public override string тит
        {
            get
            {
                // *** Start programmer edit section *** (Прикол.тит Get start)

                // *** End programmer edit section *** (Прикол.тит Get start)
                string result = base.тит;
                // *** Start programmer edit section *** (Прикол.тит Get end)

                // *** End programmer edit section *** (Прикол.тит Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Прикол.тит Set start)

                // *** End programmer edit section *** (Прикол.тит Set start)
                base.тит = value;
                // *** Start programmer edit section *** (Прикол.тит Set end)

                // *** End programmer edit section *** (Прикол.тит Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПриколE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриколE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриколE", typeof(IIS.Gfgfg.Прикол));
                }
            }
            
            /// <summary>
            /// "ПриколL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриколL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриколL", typeof(IIS.Gfgfg.Прикол));
                }
            }
        }
    }
}
