//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gfgfg
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Пример.
    /// </summary>
    // *** Start programmer edit section *** (Пример CustomAttributes)

    // *** End programmer edit section *** (Пример CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПримерE", new string[] {
            "строка as \'Строка\'",
            "номер as \'Номер\'",
            "тит as \'Тит\'"})]
    [View("ПримерL", new string[] {
            "строка as \'Строка\'",
            "номер as \'Номер\'",
            "тит as \'Тит\'"})]
    public class Пример : IIS.Gfgfg.Наслед
    {
        
        private string fстрока;
        
        private int fномер;
        
        // *** Start programmer edit section *** (Пример CustomMembers)

        // *** End programmer edit section *** (Пример CustomMembers)

        
        /// <summary>
        /// номер.
        /// </summary>
        // *** Start programmer edit section *** (Пример.номер CustomAttributes)

        // *** End programmer edit section *** (Пример.номер CustomAttributes)
        public virtual int номер
        {
            get
            {
                // *** Start programmer edit section *** (Пример.номер Get start)

                // *** End programmer edit section *** (Пример.номер Get start)
                int result = this.fномер;
                // *** Start programmer edit section *** (Пример.номер Get end)

                // *** End programmer edit section *** (Пример.номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Пример.номер Set start)

                // *** End programmer edit section *** (Пример.номер Set start)
                this.fномер = value;
                // *** Start programmer edit section *** (Пример.номер Set end)

                // *** End programmer edit section *** (Пример.номер Set end)
            }
        }
        
        /// <summary>
        /// строка.
        /// </summary>
        // *** Start programmer edit section *** (Пример.строка CustomAttributes)

        // *** End programmer edit section *** (Пример.строка CustomAttributes)
        [StrLen(255)]
        public virtual string строка
        {
            get
            {
                // *** Start programmer edit section *** (Пример.строка Get start)

                // *** End programmer edit section *** (Пример.строка Get start)
                string result = this.fстрока;
                // *** Start programmer edit section *** (Пример.строка Get end)

                // *** End programmer edit section *** (Пример.строка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Пример.строка Set start)

                // *** End programmer edit section *** (Пример.строка Set start)
                this.fстрока = value;
                // *** Start programmer edit section *** (Пример.строка Set end)

                // *** End programmer edit section *** (Пример.строка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПримерE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПримерE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПримерE", typeof(IIS.Gfgfg.Пример));
                }
            }
            
            /// <summary>
            /// "ПримерL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПримерL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПримерL", typeof(IIS.Gfgfg.Пример));
                }
            }
        }
    }
}
